version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/data

volumes:
  db_data:
