# Generated by Django 5.1 on 2024-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('wallet_address', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=7)),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
